### ISSUE TITLE
[Medical imaging] generate_engine error

### ISSUE THREAD

**Issue by lyly403** [ltechkorea/inference_results_v1.0#12]
(mlperf) sangwoo@mlperf-inference-sangwoo:/work$ make generate_engines RUN_ARGS="--benchmarks=3d-unet --scenarios=offline --config_ver=default"
[2021-07-20 13:31:54,610 init.py:255 INFO] Running command: CUDA_VISIBILE_ORDER=PCI_BUS_ID nvidia-smi --query-gpu=gpu_name,pci.device_id,uuid --format=csv
[2021-07-20 13:32:00,218 main.py:701 INFO] Detected System ID: V100S-PCIE-32GBx8
[2021-07-20 13:32:00,228 main.py:529 INFO] Using config files: configs/3d-unet/Offline/config.json
[2021-07-20 13:32:00,229 init.py:341 INFO] Parsing config file configs/3d-unet/Offline/config.json ...
[2021-07-20 13:32:00,230 main.py:542 INFO] Processing config "V100S-PCIE-32GBx8_3d-unet_Offline"
[2021-07-20 13:32:00,309 main.py:82 INFO] Building engines for 3d-unet benchmark in Offline scenario...
[2021-07-20 13:32:00,310 main.py:102 INFO] Building GPU engine for V100S-PCIE-32GBx8_3d-unet_Offline
Process Process-1:
Traceback (most recent call last):
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(self._args, **self._kwargs)
File "/work/code/main.py", line 108, in handle_generate_engine
b.build_engines()
File "/work/code/common/builder.py", line 142, in build_engines
self.initialize()
File "/work/code/3d-unet/tensorrt/3d-unet.py", line 292, in initialize
model = self.preprocess_onnx(onnx.load(self.model_path))
File "/usr/local/lib/python3.6/dist-packages/onnx/init.py", line 114, in load_model
s = _load_bytes(f)
File "/usr/local/lib/python3.6/dist-packages/onnx/init.py", line 30, in _load_bytes
with open(cast(Text, f), 'rb') as readable:
FileNotFoundError: [Errno 2] No such file or directory: 'build/models/3d-unet/3dUNetBraTS.onnx'
Traceback (most recent call last):
File "code/main.py", line 703, in
main(main_args, system)
File "code/main.py", line 634, in main
launch_handle_generate_engine(_gen_args, **_gen_kwargs)
File "code/main.py", line 62, in launch_handle_generate_engine
raise RuntimeError("Building engines failed!")
RuntimeError: Building engines failed!
Makefile:599: recipe for target 'generate_engines' failed
make: *** [generate_engines] Error 1

**Comment by lyly403** [comment]
### run_harness error
(mlperf) sangwoo@mlperf-inference-sangwoo:/work$ make run_harness RUN_ARGS="--fast --benchmarks=3d-unet --scenarios=offline --config_ver=default --test_mode=PerformanceOnly"
[2021-07-21 09:28:16,303 __init__.py:255 INFO] Running command: CUDA_VISIBILE_ORDER=PCI_BUS_ID nvidia-smi --query-gpu=gpu_name,pci.device_id,uuid --format=csv
[2021-07-21 09:28:23,790 main.py:701 INFO] Detected System ID: V100S-PCIE-32GBx8
[2021-07-21 09:28:23,798 main.py:529 INFO] Using config files: configs/3d-unet/Offline/config.json
[2021-07-21 09:28:23,799 __init__.py:341 INFO] Parsing config file configs/3d-unet/Offline/config.json ...
Traceback (most recent call last):
  File "code/main.py", line 703, in <module>
    main(main_args, system)
  File "code/main.py", line 530, in main
    configs = load_configs(config_files)
  File "/work/code/common/__init__.py", line 342, in load_configs
    configs.append(json.load(f))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 21 (char 20)
Makefile:616: recipe for target 'run_harness' failed
make: *** [run_harness] Error 1
