### ISSUE TITLE
[ BUG ] dlrm preprocess 오류 

### ISSUE THREAD

**Issue by dc0953** [ltechkorea/inference_results_v1.0#19]
## **Describe the bug**

> A clear and concise description of what the bug is.

- preprocess 오류
- 버그 설명

### **Screenshots or Logs**

```
Converting day_0, day_1, ... to day_0_reordered.npz, day_1_reordered.npz, ...
Reading raw data=/work/build/data/criteo/day
Skipping counts per file (already exist)
Skip existing /work/build/data/criteo/day_0.npz
Skip existing /work/build/data/criteo/day_1.npz
Skip existing /work/build/data/criteo/day_2.npz
Skip existing /work/build/data/criteo/day_3.npz
Skip existing /work/build/data/criteo/day_4.npz
Skip existing /work/build/data/criteo/day_5.npz
Skip existing /work/build/data/criteo/day_6.npz
Skip existing /work/build/data/criteo/day_7.npz
Skip existing /work/build/data/criteo/day_8.npz
Skip existing /work/build/data/criteo/day_9.npz
Skip existing /work/build/data/criteo/day_10.npz
Skip existing /work/build/data/criteo/day_11.npz
Skip existing /work/build/data/criteo/day_12.npz
Skip existing /work/build/data/criteo/day_13.npz
Skip existing /work/build/data/criteo/day_14.npz
Skip existing /work/build/data/criteo/day_15.npz
Skip existing /work/build/data/criteo/day_16.npz
Skip existing /work/build/data/criteo/day_17.npz
Skip existing /work/build/data/criteo/day_18.npz
Skip existing /work/build/data/criteo/day_19.npz
Skip existing /work/build/data/criteo/day_20.npz
Skip existing /work/build/data/criteo/day_21.npz
Skip existing /work/build/data/criteo/day_22.npz
Skip existing /work/build/data/criteo/day_23.npz
Total number of samples: 4373472329
Divided into days/splits:
 [195841983, 199563535, 196792019, 181115208, 152115810, 172548507, 204846845, 200801003, 193772492, 198424372, 185778055, 153588700, 169003364, 194216520, 194081279, 187154596, 177984934, 163382602, 142061091, 156534237, 193627464, 192215183, 189747893, 178274637]
Traceback (most recent call last):
  File "code/dlrm/tensorrt/preprocess_data.py", line 100, in <module>
    main()
  File "code/dlrm/tensorrt/preprocess_data.py", line 94, in main
    preprocess_dlrm(data_dir, model_dir, preprocessed_data_dir)
  File "code/dlrm/tensorrt/preprocess_data.py", line 51, in preprocess_dlrm
    True
  File "/work/code/dlrm/tensorrt/scripts/data_utils.py", line 1183, in loadDataset
    memory_map
  File "/work/code/dlrm/tensorrt/scripts/data_utils.py", line 1108, in getCriteoAdData
    processCriteoAdData(d_path, d_file, npzfile, days, convertDicts, counts)
  File "/work/code/dlrm/tensorrt/scripts/data_utils.py", line 143, in processCriteoAdData
    X_cat_t[j, k] = convertDicts[j][x]
KeyError: 38562326
Makefile:395: recipe for target 'preprocess_data' failed
make: *** [preprocess_data] Error 1
```

## **Expected behavior**

> A clear and concise description of what you expected to happen.

- 정상 동작 설명
- 정상 동작 설명

## **Possible Solution**

1. 1st solution
2. 2nd solution

## **Additional context**

> Add any other context about the problem here.

- 추가 정보
- 추가 정보

**Comment by dc0953** [comment]
생성된 npz 파일 삭제 후 전처리 재진행
- 10:50분 시작

**Comment by dc0953** [comment]
21.07.27 
12 : 00 전처리 재진행
