### ISSUE TITLE
[ BUG ] dlrm preprocess error

### ISSUE THREAD

**Issue by dc0953** [ltechkorea/inference_results_v1.0#24]
## **Describe the bug**

> A clear and concise description of what the bug is.

- train_data.bin, test_data.bin, val_data.bin 생성과정중 permission error 로 인해 생성불가

### **Screenshots or Logs**

```
Converting day_0_reordered.npz, day_1_reordered.npz, ... to train_data.bin, test_data.bin, val_data.bin ...
Running preprocessing for split = train
Traceback (most recent call last):
  File "code/dlrm/tensorrt/preprocess_data.py", line 100, in <module>
    main()
  File "code/dlrm/tensorrt/preprocess_data.py", line 94, in main
    preprocess_dlrm(data_dir, model_dir, preprocessed_data_dir)
  File "code/dlrm/tensorrt/preprocess_data.py", line 56, in preprocess_dlrm
    _preprocess(args)
  File "/work/code/dlrm/tensorrt/scripts/data_loader_terabyte.py", line 296, in _preprocess
    split=split)
  File "/work/code/dlrm/tensorrt/scripts/data_loader_terabyte.py", line 244, in numpy_to_binary
    with open(output_file_path, 'wb') as output_file:
PermissionError: [Errno 13] Permission denied: '/work/build/preprocessed_data/criteo/train_data.bin'
Makefile:398: recipe for target 'preprocess_data' failed
make: *** [preprocess_data] Error 1
make: *** [Makefile:360: launch_docker] Error 2
```

## **Expected behavior**

> A clear and concise description of what you expected to happen.

- 정상 동작 설명
- 정상 동작 설명

## **Possible Solution**

1. 1st solution
2. 2nd solution

## **Additional context**

> Add any other context about the problem here.

- 추가 정보
- 추가 정보

**Comment by jay-huh** [comment]
`/preprocess_data` 디렉토리에 `write` 권한 부여함.
